"""
Curriculum models for content ingestion and management.

These models support ingesting learning content from multiple sources:
1. School systems (API, MCP tools, manual uploads)
2. Public/open-licensed educational content
3. AI-assisted content (Intel Input from external tools)
"""

import uuid
import enum
from datetime import datetime
from sqlalchemy import Column, String, Text, Integer, Boolean, DateTime, ForeignKey, Enum, JSON, Table
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship

from app.db import Base


class ResourceType(str, enum.Enum):
    """Type of learning resource"""
    TEXT = "text"  # Text article, lesson content
    VIDEO = "video"  # Video lesson
    PDF = "pdf"  # PDF document
    INTERACTIVE_EXERCISE = "interactive_exercise"  # Interactive practice
    QUIZ = "quiz"  # Assessment/quiz
    EXTERNAL_LINK = "external_link"  # Link to external content
    AUDIO = "audio"  # Audio lesson/podcast
    IMAGE = "image"  # Image/diagram
    WORKSHEET = "worksheet"  # Downloadable worksheet
    GAME = "game"  # Educational game


class SourceType(str, enum.Enum):
    """Source of the learning resource"""
    SCHOOL_INTERNAL = "school_internal"  # Content from school's own system
    TEACHER_UPLOADED = "teacher_uploaded"  # Teacher manually uploaded
    INTEL_INPUT = "intel_input"  # AI-assisted content from external AI tools
    PUBLIC_OPEN_CONTENT = "public_open_content"  # Open educational resources (OER)
    STELLAR_AI_GENERATED = "stellar_ai_generated"  # AI-generated by Stellar AI
    THIRD_PARTY_API = "third_party_api"  # From educational content APIs


# Association table for many-to-many relationship between Resources and Skills
resource_skills = Table(
    "resource_skills",
    Base.metadata,
    Column("resource_id", UUID(as_uuid=True), ForeignKey("learning_resources.id", ondelete="CASCADE"), primary_key=True),
    Column("skill_id", UUID(as_uuid=True), ForeignKey("skills.id", ondelete="CASCADE"), primary_key=True),
)


class LearningResource(Base):
    """
    Represents a piece of learning content that can be assigned to students.

    Resources can come from multiple sources and are mapped to Skills and LearningModules.
    """
    __tablename__ = "learning_resources"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)

    # Basic information
    title = Column(String(500), nullable=False, index=True)
    description = Column(Text, nullable=True)

    # Resource type and location
    resource_type = Column(Enum(ResourceType), nullable=False, index=True)
    url = Column(String(1000), nullable=True)  # URL for external resources
    file_path = Column(String(1000), nullable=True)  # Local file path for uploaded content

    # Content metadata
    language = Column(String(10), nullable=False, default="en", index=True)
    subject = Column(String(100), nullable=True, index=True)  # e.g., "math", "reading", "science"

    # Age/grade appropriateness
    grade_min = Column(Integer, nullable=True)  # e.g., 1
    grade_max = Column(Integer, nullable=True)  # e.g., 5
    age_min = Column(Integer, nullable=True)  # e.g., 6
    age_max = Column(Integer, nullable=True)  # e.g., 12

    # Time estimate
    estimated_minutes = Column(Integer, nullable=True)  # Time to complete

    # Source information
    source_type = Column(Enum(SourceType), nullable=False, index=True)
    source_attribution = Column(Text, nullable=True)  # Original author, platform, etc.
    source_url = Column(String(1000), nullable=True)  # Original source URL if applicable
    license_type = Column(String(100), nullable=True)  # e.g., "CC BY-SA 4.0", "All Rights Reserved"

    # Who created/uploaded this resource
    created_by_user_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL"), nullable=True)
    school_id = Column(UUID(as_uuid=True), ForeignKey("schools.id", ondelete="CASCADE"), nullable=True, index=True)

    # Status and visibility
    is_active = Column(Boolean, default=True, nullable=False, index=True)
    is_public = Column(Boolean, default=False, nullable=False)  # Public resources can be shared across schools

    # Quality and engagement metrics
    difficulty_level = Column(String(50), nullable=True)  # e.g., "beginner", "intermediate", "advanced"
    quality_score = Column(Integer, nullable=True)  # 0-100, based on usage and feedback
    view_count = Column(Integer, default=0, nullable=False)
    completion_count = Column(Integer, default=0, nullable=False)

    # Additional metadata (flexible JSON for custom fields)
    resource_metadata = Column(JSON, nullable=True)
    # Examples:
    # - {"standards": ["CCSS.MATH.CONTENT.3.OA.A.1"], "keywords": ["multiplication", "arrays"]}
    # - {"prerequisites": ["basic_addition"], "learning_outcomes": ["solve_word_problems"]}
    # - {"interactive": true, "requires_login": false}

    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)

    # Relationships
    created_by = relationship("User", foreign_keys=[created_by_user_id])
    school = relationship("School")
    skills = relationship("Skill", secondary=resource_skills, back_populates="resources")

    def __repr__(self):
        return f"<LearningResource(id={self.id}, title='{self.title}', type={self.resource_type.value})>"


# Add reverse relationship to Skill model
# (This will be added to app/models/skill.py via import)
from app.models.skill import Skill
Skill.resources = relationship("LearningResource", secondary=resource_skills, back_populates="skills")
